# Read the Docs configuration file (v2)
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
