# Read the Docs configuration file (v2)
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.10"
  apt_packages:
    # chromium-browser is required by Kaleido to generate Plotly figures via fig.write_image()
    - chromium-browser
    # The following dependencies are suggested by choreographer (a dependency of Kaleido)
    # see: https://github.com/plotly/choreographer/blob/main/choreographer/browsers/_errors.py
    - libnss3
    - libatk-bridge2.0-0
    - libcups2
    - libxcomposite1
    - libxdamage1
    - libxfixes3
    - libxrandr2
    - libgbm1
    - libxkbcommon0
    - libpango-1.0-0
    - libcairo2
    - libasound2

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
