# Read the Docs configuration file (v2)
# ref: https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.9"
  apt_packages:
    # chromium-browser is required by Kaleido to generate Plotly figures via fig.write_image()
    - chromium-browser

python:
  install:
    - requirements: requirements/docs.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/conf.py

formats:
  - htmlzip
  - pdf
