[mypy]

# Import discovery  ---
files = src/ridgeplot, tests, scripts, examples

# Disallow dynamic typing  ---
;disallow_any_unimported = True
disallow_subclassing_any = True

# Untyped definitions and calls  ---
disallow_untyped_calls = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
disallow_untyped_decorators = True

# None and Optional handling  ---
no_implicit_optional = True

# Configuring warnings  ---
warn_redundant_casts = True
warn_unused_ignores = True
warn_return_any = True
warn_unreachable = True

# Miscellaneous strictness flags  ---
strict_equality = True

# Configuring error messages  ---
show_error_codes = True

# Advanced options  ---
plugins = numpy.typing.mypy_plugin
;pdb = True
;show_traceback = True
;raise_exceptions = True

[mypy-plotly.*]
ignore_missing_imports = True
[mypy-_plotly_utils.*]
ignore_missing_imports = True
[mypy-statsmodels.*]
ignore_missing_imports = True
[mypy-pandas.*]
ignore_missing_imports = True

[mypy-markdown_it.*]
ignore_missing_imports = True
[mypy-mdformat.*]
ignore_missing_imports = True
