---
name: "🐛 Bug report"
description: "Report an issue you encountered with ridgeplot"
title: "[BUG] "
labels: [ "bug" ]
body:
  - type: markdown
    attributes:
      value: |
        **Thank you for your interest in improving ridgeplot!** 🚀

        We really appreciate you taking the time to help make this project better for everyone.

        We organize issues into two main categories:
        - ⭐ **Feature request**: Suggest a new idea or enhancement to ridgeplot
        - 🐛 **Bug report**: Report an issue you encountered with ridgeplot

        Looks like you're about to submit a bug report.
        Please use the template below and provide as much detail as you can.
        The more information you provide, the easier it will be for us to understand and reproduce the issue you encountered.

        For broader discussions, questions, or general feedback, please head over to our [GitHub Discussions](https://github.com/tpvasconcelos/ridgeplot/discussions) page.

        Please note that this is a volunteer-run project, and we may not be able to respond to every issue or pull request immediately.
        Our response time may vary, but we appreciate your patience and will try to get back to you as soon as possible.

  - type: markdown
    attributes:
      value: |
        ---

        ## Environment information

        Please use the dropdown menus and input fields below to provide information about your environment.
        This information will help us reproduce the issue you encountered and identify potential causes.

        To find the version of ridgeplot you're using, you can run `pip show ridgeplot` in your terminal, or
        alternatively: `python -c "import ridgeplot; print(ridgeplot.__version__)"`.

        To find the version of Python you're using, you can run `python --version` in your terminal.
  - type: input
    attributes:
      label: "ridgeplot version"
      placeholder: "major.minor.patch"
    validations:
      required: true
  - type: input
    attributes:
      label: "Python version"
      placeholder: "major.minor.patch"
    validations:
      required: true
  - type: dropdown
    attributes:
      label: "Operating system"
      options:
        - "Windows"
        - "macOS"
        - "Linux"
        - "Other 🤓"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---

        ## Description

        Please provide a clear and detailed explanation of the issue you experienced, including what you expected to happen instead.

        To help us pinpoint the problem, please include:
        - A minimal, reproducible example that demonstrates the issue.
        - Any error messages, stack traces, or other relevant information.
        - If possible, add a screenshot of the plot generated by ridgeplot on your system. You can easily attach files by dragging and dropping them here.
  - type: textarea
    attributes:
      label: "Description"
    validations:
      required: true

  - type: markdown
    attributes:
      value: ---
  - type: checkboxes
    attributes:
      label: "Are you willing to submit PR?"
      description: |
        This totally optional, but if you’re interested, we’d love to help guide you through the process, especially if you already have a good idea of how to implement the feature.

        If you'd like to contribute, check the box below and take a look at our [contributing guidelines](https://ridgeplot.readthedocs.io/en/latest/development/contributing.html) for more details.
      options:
        - label: Yes I am willing to submit a PR! 🚀

  - type: markdown
    attributes:
      value: |
        ---

        **Thank you for taking the time to report this issue!** 🙏

        We will get back to you as soon as possible.
