name: Publish to PyPI

on:
  release:
    types:
      - published

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python
        with:
          python-version: "3.8"
          requirements: tox
      - name: Package and upload a release to test PyPI
        env:
          TWINE_PASSWORD: "${{ secrets.PYPI_TOKEN_TEST }}"
        run: tox -e build,publish-pypi-test
      - name: Package and upload a release prod PyPI
        env:
          TWINE_PASSWORD: "${{ secrets.PYPI_TOKEN }}"
        run: tox -e build,publish-pypi-prod
